### ISSUE TITLE
Пример работы с readTable

### ISSUE THREAD

**Issue by jumper423** [yandex-cloud/ydb-php-sdk#10]
Пожалуйста, напишите реальный пример работы с методом readTable.

Интересны такие случаи

1. Получение всей таблицы целиком и обработка этих данных
2. Постраничная обработка всей таблицы и обработка этих данных
3. Если возможно, то получение конкретного диапазона строк или перечисленных id строк, получение их и обработка

**Comment by jumper423** [comment]
@alshabalin @ZooKeeper 
Пытаюсь так 
```
$params['key_range'] = (new KeyRange())
    ->setLessOrEqual((new TypedValue([
        'type' => new Type(['tuple_type' => new TupleType()]),
        'value' => new Value([
            'uint32_value' => 10,
        ]),
    ])));

return $this->streamRequest('StreamReadTable', $params);
```
но всё равно достаются записи где PK больше 10.

**Comment by alshabalin** [comment]
Опция key_range добавлена.
