### ISSUE TITLE
PHP 8.0 composer. lcobucci/jwt 3.4.6 requires php ^5.6 || ^7.0 -> your php version (8.0.11) does not satisfy that requirement.

### ISSUE THREAD

**Issue by jumper423** [yandex-cloud/ydb-php-sdk#15]
Использование PHP 8.0 приводит к ошибке

===> executing build script
===> composer.json/composer.lock found in sources
===> will start 'composer install --no-dev' in /function/code
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - lcobucci/jwt is locked to version 3.4.6 and an update of this package was not requested.
    - lcobucci/jwt 3.4.6 requires php ^5.6 || ^7.0 -> your php version (8.0.11) does not satisfy that requirement.
  Problem 2
    - lcobucci/jwt 3.4.6 requires php ^5.6 || ^7.0 -> your php version (8.0.11) does not satisfy that requirement.
    - yandex-cloud/ydb-php-sdk v1.1.1 requires lcobucci/jwt ^3.4.6 -> satisfiable by lcobucci/jwt[3.4.6].
    - yandex-cloud/ydb-php-sdk is locked to version v1.1.1 and an update of this package was not requested.

===> execution failed: exit status 2

**Comment by ZooKeeper** [comment]
Please try new sdk version 1.2. It supports php8
