### ISSUE TITLE
Обновление через композер не доставляет последних изменений кода

### ISSUE THREAD

**Issue by twinpigs** [yandex-cloud/ydb-php-sdk#3]
На странице https://packagist.org/packages/yandex-cloud/ydb-php-sdk не представлен тэг v1.0.3 и присутствует пометка:

This package is not auto-updated.
Last update: 2021-05-07 09:48:34 UTC

Таким образом свежие исправления не могут быть использованы при рекомендованой установке SDK через композер.

**Comment by ZooKeeper** [comment]
Спасибо! Поправили
