### ISSUE TITLE
Call to a member function `getTxMeta()` on `null`

### ISSUE THREAD

**Issue by vdmorozov** [yandex-cloud/ydb-php-sdk#4]
It's possible that the `$result` variable remains unset in `Session::beginTransaction`. That leads to the "call on null" error when getting metadata from the request's result:

```php
        $result = $this->request('BeginTransaction', [
            'session_id' => $this->session_id,
            'tx_settings' => $transaction_settings,
        ]);

        $tx_id = $result->getTxMeta()->getId();
```

**Comment by ZooKeeper** [comment]
Thanks for the report. We've added the check in this commit.
https://github.com/yandex-cloud/ydb-php-sdk/commit/d954a00e02c525fc2f1916a178b42cbbbb823d3b
