### ISSUE TITLE
QueryCachePolicy как изменить keep_in_cache

### ISSUE THREAD

**Issue by jumper423** [yandex-cloud/ydb-php-sdk#7]
Объект класса `QueryCachePolicy` создаётся прямо в методе query и достучаться и вызвать метод setKeepInCache нет.

Тогда как изменить параметр keep_in_cache, для того чтобы закешировать запрос?

**Comment by alshabalin** [comment]
Действительно, сейчас этого нет.

Добавим возможность управления на QueryCachePolicy.

**Comment by alshabalin** [comment]
Добавлен метод `keepInCache()` для Session:

```php
$result = $table->session()->keepInCache()->query('select * from users;');
```

`keepInCache` может принимать аргумент (true или false) для включения/отключения опции.
